"""add avatar_url

Revision ID: 30b03601290c
Revises: 001_initial
Create Date: 2026-07-06 00:03:45.609800

"""

from alembic import op
import sqlalchemy as sa



revision = '30b03601290c'
down_revision = '001_initial'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamification_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_settings_key'), 'gamification_settings', ['key'], unique=True)
    op.create_table('homepage_content',
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cta_text', sa.String(length=255), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_content_section'), 'homepage_content', ['section'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.alter_column('achievements', 'achievement_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EXPLORER', 'SCHOLAR', 'COLLECTOR', 'COMPLETIONIST', name='achievement_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('historical_documents', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PRIMARY', 'SECONDARY', 'ARCHAEOLOGICAL', name='document_source_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('progress', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('QUEST', 'ARTIFACT', 'CITY', 'QUIZ', name='progress_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('progress', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='progress_quest_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('quests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='quest_status', native_enum=False),
               existing_nullable=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('GUEST', 'USER', 'ADMIN', name='user_role', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('GUEST', 'USER', 'ADMIN', name='user_role', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'avatar_url')
    op.alter_column('quests', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='quest_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('progress', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='progress_quest_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('progress', 'entity_type',
               existing_type=sa.Enum('QUEST', 'ARTIFACT', 'CITY', 'QUIZ', name='progress_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('historical_documents', 'source_type',
               existing_type=sa.Enum('PRIMARY', 'SECONDARY', 'ARCHAEOLOGICAL', name='document_source_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('achievements', 'achievement_type',
               existing_type=sa.Enum('EXPLORER', 'SCHOLAR', 'COLLECTOR', 'COMPLETIONIST', name='achievement_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_homepage_content_section'), table_name='homepage_content')
    op.drop_table('homepage_content')
    op.drop_index(op.f('ix_gamification_settings_key'), table_name='gamification_settings')
    op.drop_table('gamification_settings')
    op.drop_table('gallery_images')
    # ### end Alembic commands ###